export const personalInfo = {
  name: "Habibullah Hibatul Wafi",
  displayName: "Habib Wafi",
  initials: "HW",
  title: "Full Stack Developer & Blockchain Engineer",
  subtitle: "IT Professional & AI Enthusiast",
  bio: "Passionate about building clean, data-driven systems and meaningful digital experiences. Profesional Full Stack Developer yang terus mengembangkan keahlian di bidang IT, AI, dan Blockchain mengikuti perkembangan zaman.",
  location: "Jakarta, Indonesia",
  status: "Open to full-time roles, internships, and freelance projects.",
  availableForWork: true,
  email: "habibwafi96@gmail.com",
  github: "https://github.com/HabibWafi",
  linkedin: "https://www.linkedin.com/in/habibullah-hibatul-wafi",
  instagram: "https://instagram.com/habibwafi83",
  whatsapp: "6281234567890",
};

export const stats = [
  { label: "Years Experience", value: "2+" },
  { label: "Projects Built", value: "10+" },
  { label: "Technologies", value: "15+" },
];

export const skills = [
  {
    category: "Frontend",
    color: "blue",
    bgClass: "bg-blue-50",
    textClass: "text-blue-700",
    borderClass: "border-blue-200",
    dotClass: "bg-blue-500",
    items: ["React.js", "Next.js", "TypeScript", "JavaScript", "HTML5", "CSS3", "Tailwind CSS"],
  },
  {
    category: "Backend",
    color: "emerald",
    bgClass: "bg-emerald-50",
    textClass: "text-emerald-700",
    borderClass: "border-emerald-200",
    dotClass: "bg-emerald-500",
    items: ["Node.js", "Express.js", "Python", "PHP", "Laravel", "REST API"],
  },
  {
    category: "Database",
    color: "violet",
    bgClass: "bg-violet-50",
    textClass: "text-violet-700",
    borderClass: "border-violet-200",
    dotClass: "bg-violet-500",
    items: ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
  },
  {
    category: "Blockchain",
    color: "amber",
    bgClass: "bg-amber-50",
    textClass: "text-amber-700",
    borderClass: "border-amber-200",
    dotClass: "bg-amber-500",
    items: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts", "Hardhat"],
  },
  {
    category: "Data & AI",
    color: "rose",
    bgClass: "bg-rose-50",
    textClass: "text-rose-700",
    borderClass: "border-rose-200",
    dotClass: "bg-rose-500",
    items: ["Python", "R", "Machine Learning", "Data Mining", "TensorFlow", "Pandas", "Tableau"],
  },
  {
    category: "DevOps & Tools",
    color: "slate",
    bgClass: "bg-slate-100",
    textClass: "text-slate-700",
    borderClass: "border-slate-200",
    dotClass: "bg-slate-500",
    items: ["Git & GitHub", "Docker", "Linux", "VS Code", "GitHub Actions"],
  },
];

export const experiences = [
  {
    company: "BPS Kabupaten Musi Rawas",
    companyShort: "BPS Musi Rawas",
    position: "Pranata Komputer Ahli Pertama",
    period: "Oktober 2023 – Sekarang",
    current: true,
    description: [
      "Mengelola dan mengembangkan sistem informasi statistik daerah",
      "Membangun aplikasi web untuk pengolahan dan visualisasi data statistik",
      "Memberikan dukungan teknis IT kepada unit kerja dan mitra terkait",
      "Mengembangkan solusi digital untuk peningkatan efisiensi operasional",
    ],
  },
];

export const projects = [
  {
    title: "BPS Statistical Dashboard",
    description:
      "Web dashboard interaktif untuk visualisasi dan analisis data statistik Kabupaten Musi Rawas. Dilengkapi berbagai jenis chart, laporan dinamis, dan fitur ekspor data.",
    tech: ["Next.js", "TypeScript", "Chart.js", "PostgreSQL", "Tailwind CSS"],
    github: "#",
    live: "/projects/bps-dashboard",
    featured: true,
  },
  {
    title: "AI Analytics Platform",
    description:
      "Platform analitik berbasis machine learning untuk prediksi tren dan analisis data mendalam. Menggunakan model AI modern untuk menghasilkan insight yang akurat dan actionable.",
    tech: ["Python", "TensorFlow", "FastAPI", "React", "Docker"],
    github: "#",
    live: "/projects/ai-analytics",
    featured: true,
  },
  {
    title: "DeFi Smart Contract",
    description:
      "Smart contract DeFi dengan fitur staking, token swap, dan liquidity pool. Dibangun di atas Ethereum dengan standar keamanan tinggi dan gas optimization.",
    tech: ["Solidity", "Ethereum", "Web3.js", "Hardhat", "React"],
    github: "#",
    live: "/projects/defi",
    featured: true,
  },
  {
    title: "E-Commerce Platform",
    description:
      "Platform e-commerce full stack dengan manajemen produk, keranjang belanja, integrasi payment gateway, dan dashboard admin yang komprehensif.",
    tech: ["Next.js", "Node.js", "PostgreSQL", "Tailwind CSS"],
    github: "#",
    live: "/projects/ecommerce",
    featured: false,
  },
];

export const portfolioItems = [
  {
    id: "property-agent",
    title: "Agen Property",
    subtitle: "Prime Realty Indonesia",
    category: "Landing Page",
    description: "Website agen properti modern dengan listing rumah, apartemen, dan ruko. Dilengkapi search & filter canggih, profil agen, dan fitur virtual tour.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    color: "blue",
    accentColor: "from-blue-600 to-blue-800",
    bgColor: "bg-blue-50",
    textColor: "text-blue-700",
    borderColor: "border-blue-200",
    icon: "🏠",
  },
  {
    id: "restaurant",
    title: "Restoran & Kuliner",
    subtitle: "Serai Kitchen",
    category: "Landing Page",
    description: "Website restoran elegan dengan menu interaktif, sistem reservasi online, galeri foto makanan, dan integrasi Google Maps.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    color: "amber",
    accentColor: "from-amber-600 to-orange-700",
    bgColor: "bg-amber-50",
    textColor: "text-amber-700",
    borderColor: "border-amber-200",
    icon: "🍽️",
  },
  {
    id: "hotel",
    title: "Hotel & Resort",
    subtitle: "Seruni Resort & Spa",
    category: "Company Profile",
    description: "Website hotel mewah dengan booking engine, galeri kamar interaktif, fasilitas resort, dan sistem review tamu.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    color: "teal",
    accentColor: "from-teal-600 to-emerald-700",
    bgColor: "bg-teal-50",
    textColor: "text-teal-700",
    borderColor: "border-teal-200",
    icon: "🏨",
  },
  {
    id: "umkm",
    title: "UMKM & Toko Online",
    subtitle: "Batik Sekar Nusantara",
    category: "E-Commerce",
    description: "Toko online UMKM lokal dengan katalog produk, keranjang belanja, pemesanan via WhatsApp, dan cerita brand yang menarik.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    color: "rose",
    accentColor: "from-rose-600 to-red-700",
    bgColor: "bg-rose-50",
    textColor: "text-rose-700",
    borderColor: "border-rose-200",
    icon: "🛍️",
  },
  {
    id: "export-import",
    title: "Ekspor Impor",
    subtitle: "Nusantara Global Trade",
    category: "Company Profile",
    description: "Website perusahaan trading internasional dengan katalog komoditas, proses ekspor step-by-step, statistik bisnis, dan form inquiry.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    color: "indigo",
    accentColor: "from-indigo-600 to-blue-800",
    bgColor: "bg-indigo-50",
    textColor: "text-indigo-700",
    borderColor: "border-indigo-200",
    icon: "🌏",
  },
  {
    id: "company-profile",
    title: "Profil Perusahaan",
    subtitle: "TechSolusi Indonesia",
    category: "Company Profile",
    description: "Website company profile profesional dengan layanan, tim, milestone perusahaan, client showcase, dan CTA yang kuat.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    color: "violet",
    accentColor: "from-violet-600 to-purple-800",
    bgColor: "bg-violet-50",
    textColor: "text-violet-700",
    borderColor: "border-violet-200",
    icon: "🏢",
  },
  {
    id: "personal-profile",
    title: "Profil Pribadi / Dokter",
    subtitle: "Dr. Aditya Pratama, Sp.OG",
    category: "Landing Page",
    description: "Website profil profesional untuk dokter, konsultan, atau pengacara. Dengan jadwal praktek, layanan, artikel, dan form buat janji.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript"],
    color: "emerald",
    accentColor: "from-emerald-600 to-green-700",
    bgColor: "bg-emerald-50",
    textColor: "text-emerald-700",
    borderColor: "border-emerald-200",
    icon: "👨‍⚕️",
  },
];

export const education = [
  {
    institution: "Politeknik Statistika STIS",
    institutionEn: "STIS Polytechnic of Statistics",
    degree: "D4 — Sarjana Terapan Statistik (S.Tr.Stat)",
    field: "Komputasi Statistik — Sistem Informasi",
    period: "2019 – 2023",
    highlights: [
      "Specializing in Statistical Computing and Information Systems",
      "Coursework: Data Structures, Algorithms, Database Systems, Web Development",
      "Coursework: Statistics, Machine Learning, Data Mining, Data Visualization",
      "Active in software development and data analysis projects",
    ],
  },
];
